-- ASH Inspection App — Initial Schema
-- Phase 1: Foundation

-- ─── Extensions ──────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─── Section key enum ────────────────────────────────────────────────────────
-- template_order: external_approach=1, grounds=2, bin_store=3, car_park=4,
--   external_fabric=5, roof=6, communal_entrance=7, stairwells=8,
--   lifts=9, plant_room=10, internal_communal=11, additional=12
CREATE TYPE section_key AS ENUM (
  'external_approach',
  'grounds',
  'bin_store',
  'car_park',
  'external_fabric',
  'roof',
  'communal_entrance',
  'stairwells',
  'lifts',
  'plant_room',
  'internal_communal',
  'additional'
);

-- ─── User profiles ───────────────────────────────────────────────────────────
-- Extends auth.users. Created automatically by trigger on signup.
CREATE TABLE public.users (
  id          UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name   TEXT        NOT NULL,
  email       TEXT        NOT NULL,
  role        TEXT        NOT NULL DEFAULT 'inspector'
                          CHECK (role IN ('inspector', 'admin')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-create profile when a new auth user is created.
-- Caller must pass full_name in raw_user_meta_data when inviting/creating users.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.users (id, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.email
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ─── Properties ──────────────────────────────────────────────────────────────
-- Seeded from CSV. Never auto-generated by the app.
CREATE TABLE public.properties (
  id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  ref                TEXT        NOT NULL UNIQUE,
  name               TEXT        NOT NULL,
  management_company TEXT        NOT NULL,
  block_type         TEXT        NOT NULL,
  address            TEXT        NOT NULL,
  number_of_units    INTEGER     NOT NULL,
  manager_name       TEXT        NOT NULL,  -- matches users.full_name
  has_car_park       BOOLEAN     NOT NULL DEFAULT false,
  has_lift           BOOLEAN     NOT NULL DEFAULT false,
  has_roof_access    BOOLEAN     NOT NULL DEFAULT false,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Inspections ─────────────────────────────────────────────────────────────
CREATE TABLE public.inspections (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id      UUID        NOT NULL REFERENCES public.properties(id),
  inspector_id     UUID        NOT NULL REFERENCES public.users(id),
  status           TEXT        NOT NULL DEFAULT 'active'
                               CHECK (status IN ('active', 'completed', 'report_generated')),
  start_time       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  end_time         TIMESTAMPTZ,
  weather          TEXT,
  next_inspection  TEXT,
  report_docx_url  TEXT,
  report_pdf_url   TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Observations ────────────────────────────────────────────────────────────
CREATE TABLE public.observations (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  inspection_id       UUID        NOT NULL REFERENCES public.inspections(id) ON DELETE CASCADE,
  property_id         UUID        NOT NULL REFERENCES public.properties(id),
  section_key         section_key NOT NULL,
  template_order      INTEGER     NOT NULL,
  raw_narration       TEXT,
  processed_text      TEXT,
  action_text         TEXT,
  risk_level          TEXT        CHECK (risk_level IN ('High', 'Medium', 'Low')),
  responsibility      TEXT,
  classification_conf TEXT        CHECK (classification_conf IN ('auto', 'manual')),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Photos ──────────────────────────────────────────────────────────────────
CREATE TABLE public.photos (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  observation_id   UUID        NOT NULL REFERENCES public.observations(id) ON DELETE CASCADE,
  inspection_id    UUID        NOT NULL REFERENCES public.inspections(id) ON DELETE CASCADE,
  storage_path     TEXT,
  local_path       TEXT,
  caption          TEXT,
  opus_description JSONB,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Row Level Security ───────────────────────────────────────────────────────
ALTER TABLE public.users       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photos      ENABLE ROW LEVEL SECURITY;

-- users: own profile only
CREATE POLICY "users_select_own" ON public.users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "users_update_own" ON public.users
  FOR UPDATE USING (auth.uid() = id);

-- properties: inspectors see properties where manager_name = their full_name;
--             admins see all
CREATE POLICY "properties_select" ON public.properties
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = auth.uid()
        AND (u.role = 'admin' OR u.full_name = properties.manager_name)
    )
  );

-- admins can update property flags (has_car_park etc.)
CREATE POLICY "properties_update_admin" ON public.properties
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
  );

-- inspections: own records only
CREATE POLICY "inspections_all_own" ON public.inspections
  FOR ALL USING (inspector_id = auth.uid());

-- observations: accessible when the parent inspection belongs to the current user
CREATE POLICY "observations_all_own" ON public.observations
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.inspections i
      WHERE i.id = inspection_id AND i.inspector_id = auth.uid()
    )
  );

-- photos: same as observations
CREATE POLICY "photos_all_own" ON public.photos
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.inspections i
      WHERE i.id = inspection_id AND i.inspector_id = auth.uid()
    )
  );

-- ─── Storage bucket ───────────────────────────────────────────────────────────
-- Create via Supabase dashboard: name = inspection-files, public = false
-- File paths: /{property_id}/{inspection_id}/{photo_id}.jpg
--             /{property_id}/{inspection_id}/report.docx
--             /{property_id}/{inspection_id}/report.pdf
